### PR TITLE
Bump the gomod-dependencies group across 1 directory with 2 updates

### PR DESCRIPTION
**Pull request by yswe**
Address the need for manual CRD refresh after dependabot Go module updates. No hooks exist currently for dependabot PRs, so we need to make this manually.

Original PR: #23.

### CODE REVIEW

**Comment by bowei** [comment]
What do we need to do to enable dependabot?

/lgtm
/approve

**Comment by yswe** [comment]
It looks like we can automate Dependabot using GitHub Actions! Here's the documentation: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

Here is the original thread with the discussion https://github.com/dependabot/dependabot-core/issues/1758.

I missed it somehow when I was adding it. I will verify if it fits our needs.

**Comment by rikatz** [comment]
@bowei @yswe did you had to enable github actions to be able to write on the repo? (this is a repository settings at Settings / Actions / General)

Thanks!

**Pull request merged**
